#!/bin/bash
set -ex

# DockerHub Automated Build를 위한 Custom Environment Hook
# 빌드 시에 사용자 환경변수를 전달한다

docker build \
    --build-arg ELS_HOST="${ELS_HOST}" \
    --build-arg ELS_USER="${ELS_USER}" \
    --build-arg ELS_PASSWORD="${ELS_PASSWORD}" \
    --build-arg ELS_INDEX="${ELS_INDEX}" \
    --build-arg BROKER="${BROKER}" \
    --build-arg TOPICS="${TOPICS}" \
    --build-arg NOUNS_API="${NOUNS_API}" \
    --build-arg ConsumerGroup="${ConsumerGroup}" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
